version: '3'
services:
  envoy:
    image: istio/proxyv2:1.20.3
    entrypoint:
      - /usr/local/bin/envoy
      - -c
      - /etc/envoy/envoy.yaml
    ports:
      - 10000:10000
    volumes:
      - ./config/envoy.yaml:/etc/envoy/envoy.yaml

  ext-proc:
    build:
      context: .
      platforms:
        - "linux/amd64"
      dockerfile: Dockerfile
    develop:
      watch:
        - action: rebuild
          path: cmd
          ignore: ["**/*_test.go"]
        - action: rebuild
          path: pkg
          ignore: ["**/*_test.go"]
    ports:
      - 9000:9000
